import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const siteRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = resolve(siteRoot, "content");
const outputPath = resolve(siteRoot, "generated/docs-content.ts");
const locales = ["en", "ru", "zh"];

function normalizeSlash(value) {
  return value.split(sep).join("/");
}

function walkMarkdown(directory, base = directory) {
  return readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const absolute = resolve(directory, entry.name);
      if (entry.isDirectory()) return walkMarkdown(absolute, base);
      if (!entry.name.endsWith(".md") || entry.name === "SUMMARY.md") return [];
      return [normalizeSlash(relative(base, absolute))];
    })
    .sort();
}

const documents = Object.fromEntries(
  locales.map((locale) => {
    const localeRoot = resolve(contentRoot, locale);
    const entries = Object.fromEntries(
      walkMarkdown(localeRoot).map((sourcePath) => [
        sourcePath,
        readFileSync(resolve(localeRoot, sourcePath), "utf8")
      ])
    );
    return [locale, entries];
  })
);

const summaries = Object.fromEntries(
  locales.map((locale) => [
    locale,
    readFileSync(resolve(contentRoot, locale, "SUMMARY.md"), "utf8")
  ])
);

const englishPaths = Object.keys(documents.en);
for (const locale of locales.slice(1)) {
  const localizedPaths = Object.keys(documents[locale]);
  const missing = englishPaths.filter((sourcePath) => !(sourcePath in documents[locale]));
  const extra = localizedPaths.filter((sourcePath) => !(sourcePath in documents.en));
  if (missing.length || extra.length) {
    throw new Error(
      [
        `Documentation parity failed for ${locale}.`,
        missing.length ? `Missing: ${missing.join(", ")}` : "",
        extra.length ? `Extra: ${extra.join(", ")}` : ""
      ]
        .filter(Boolean)
        .join(" ")
    );
  }
}

const generated = [
  "/* This file is generated by scripts/generate-content.mjs. */",
  "",
  `export const generatedSummaries: Readonly<Record<"en" | "ru" | "zh", string>> = ${JSON.stringify(summaries, null, 2)};`,
  "",
  `export const generatedDocuments: Readonly<Record<"en" | "ru" | "zh", Readonly<Record<string, string>>>> = ${JSON.stringify(documents, null, 2)};`,
  ""
].join("\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, generated);
console.log(
  `Generated ${englishPaths.length} pages in ${locales.length} languages`
);
